### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by ginsterbusch** [zdroid/codify.css#6]
Yep. It's QUITE misleading. Sanitization is for cleaning up input and avoiding security holes. NOT for CSS normalization.

Thus I'd suggest something else, just NOT "sanitize" ;)

cu, w0lf.

**Comment by ZDroid** [comment]
Thank you for the suggestion, I'll think about it.

2015-01-24 2:38 GMT+01:00 Fabian Wolf <notifications@github.com>:

> Yep. It's QUITE misleading. Sanitization is for cleaning up input and
> avoiding security holes. NOT for CSS normalization.
>
> Thus I'd suggest something else, just NOT "sanitize" ;)
>
> cu, w0lf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZDroid/sanitize.css/issues/6>.
>



-- 
Zlatan Vasović - *ZDroid*

**Comment by ZDroid** [comment]
@ginsterbusch I am interested to solve this issue. Do you have some suggestion for the name? This project is still young so name changes wouldn't be a *disaster*.

**Comment by corysimmons** [comment]
@ZDroid Would you mind changing the name of the project to something else? https://github.com/10up/sanitize.css is a css reset just like this project, with the exact same name, and it has 1k+ stars and is very active.

I ask because I'd like to get https://github.com/10up/sanitize.css put on cdnjs in place of this lib.

Would this be something you'd be interested in accommodating?

**Comment by ZDroid** [comment]
Okay, I will try to find a new name then.

**Comment by corysimmons** [comment]
Awesome, thank you! :)

**Comment by thasmo** [comment]
What's the state on this? I encourage your contribution to the open source world by creating this library but I think it would also benefit your project, if you rename it.

**Comment by ZDroid** [comment]
@thasmo Just tell the cdnjs team to change my project's name on cdnjs to zdroid-sanitize.css or whatever. I won't bother much on changing the name there.

**Comment by zdroid** [comment]
I've decided to change project's name to **codify.css**. I hope that resolves your issue.

**Comment by corysimmons** [comment]
@jonathantneal Not sure if you want to add your lib to cdnjs/bower/etc. as `sanitize.css`, but this lib isn't causing a conflict anymore.

**Comment by zdroid** [comment]
@corysimmons @jonathantneal  I have proposed pull request with name change to JSDelivr, I'll propose it to cdnjs too (soon, as doing anything in almost 1 GB repository is damn slow). I published bower module with new name, so you'll have to ask Bower team to unpublish the one with sanitize.css name.

It should be good enough. I hope we can collaborate in future.

**Comment by corysimmons** [comment]
Super nice of you @zdroid
